version: '4.4.4'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26272xyz
      POSTGRES_DB: nest
    networks: 
      - freecodecamp
networks:
  freecodecamp: